class KMS < SitePrism::Page
	set_url 'https://backend.diginn-kds.domain4now.com/admin/login'
	element :login_text_before, 'body > div > div > div > div.main-data > div > div > h3' #Find "Please Login" text on the page
	element :email, :id => 'admin_email'
	element :password, :id => 'admin_password'
	element :login_button, '#new_admin > div.actions > input' #Find "Log in" button on the page
	element :close_button, 'button[class="close"]'
	element :hq_store, :id => 'edit_store_3'
	elements :hq, :xpath, '//a[text()="HQ"]'
	element :hq_store_checkbox, :xpath, '/html/body/div/div/div/div[3]/table/tbody/tr[3]/td[5]/div/form/input[4]'
	element :search_bar, '#store_search > div > div.col-sm-4 > span > span.selection > span > ul > li > input'
	element :search_result, '#select2-store_group_ids-results'
	element :search_button, '[name="commit"]'
	element :system_config, '#navbarSupportedContent > ul.navbar-nav.mr-auto > li:nth-child(6)'
	element :system_config_screen, 'input[id="system_configuration_uber_auth_code"]'
	element :menu_management, '#navbarSupportedContent > ul.navbar-nav.mr-auto > li:nth-child(5)'
	element :menu_management_table, 'body > div > div > div > div.main-data'
	element :mm_search_bar, 'input[class="select2-search__field"]'
	element :select_doordash, :xpath, '//li[text()="Doordash"]'
	element :search_revenue_centre, :id => 'name_cont'
	element :selected_result, 'body > div.container-fluid.mt-4 > div > div > div.main-data > table > tbody > tr > td:nth-child(1)'
	elements :store_groups, '[class="nav-item dropdown"]'
	element :store_group_list_dd, :xpath, '//a[text()="Store Groups List"]'
	element :store_group_list, :xpath, '//a[text()="Default Store Group"]'
	element :store_group_name, :id => "store_group_name"
	element :store_group_create, '[class="btn btn-sm btn-success"]'
	element :ot_list_dd, :xpath, '//a[text()="OT List"]'
	element :three_pp_list_dd, :xpath, '//a[text()="3pp List"]'
	element :three_pp_mapping_dd, :xpath, '//a[text()="3pp Mapping"]'
	element :service_type, 'input[placeholder="Select Service Types"]'
	element :select_olo, :xpath, '//li[text()="Olo"]'
	element :search_shortname, 'input[placeholder="Select Short Names"]'
	element :hq_dd, :xpath, '//li[text()="HQ"]'
	element :hq_show_page, '[class="col-md-12"]'
	element :select_services, 'input[placeholder="Select Services"]'
	element :grubhub_service, :xpath, '//li[text()="Grubhub"]'
	elements :grubhub_result, :xpath, '//td[text()="Grubhub"]'
	elements :selection_dds, '[class="select2-selection__rendered"]'
	elements :gh_dd, '[class="select2-results__option"]'
	element :stores_list, :xpath, '//a[text()="Stores List"]'
	element :select_store_groups, 'input[placeholder="Select Store Groups"]'
	element :rev_heading, :id => 'store_store_group_id'
	element :total_orders_link, '[name="total_orders"]'
	element :total_orders, 'body > div.container-fluid.mt-4 > div > div > div.main-data > div > div:nth-child(1) > div:nth-child(1) > div > table > tbody > tr:nth-child(6) > td:nth-child(2) > a'
	element :order_search, 'input[placeholder="Source Id"]'
	elements :order_count, '[name="order_source_id"]'
	element :view_order, 'body > div.container-fluid.mt-4 > div > div > div.main-data > table > tbody > tr > td:nth-child(1) > a'
	element :order_summary_kms, '[class="col-md-6"]'
	element :cancel_button, '[class="btn btn-danger btn-sm"]'
	element :alert_message, '[class="alert alert-success auto-disappear"]'
	elements :items_dd, '[class="nav-link"]'
	element :card_body, '[class="card-body"]'
	element :ot_category_field, 'input[placeholder="Filter Category OT Name"]'
	element :search_item_name, 'input[placeholder="Search"]'
	element :select_item, 'body > div.container-fluid.mt-4 > div > div > div.main-data > table > tbody > tr:nth-child(1) > td:nth-child(4) > a'
	element :item_details, 'select[id="store_group_id_eq"]'
	elements :save_button, '[value="Save"]'
	element :menu_id, 'input[id="item_menu_ids"]'
	element :add_mod, 'input[name="item_setting[show_additional_modifiers]"]'
	element :add_mod_dd, 'select[id="item_setting_item_additional_modifier_groups_attributes_0_modifier_group_id"]'
	element :mod_items, 'input[placeholder="Select Additional Modifiers"]'
	element :mod_items_dd, '[class="select2-results__option select2-results__option--highlighted"]'
	element :remove_button, '[class="btn btn-danger btn-sm"]'
	element :separate_ticket, 'input[name="item_setting[show_individually]"]'
	element :end_section, 'select[id="item_setting_section_id"]'
	element :table_class, '[class="table sticky-header table-striped table-bordered table-hover"]'
	element :s_button, '[value="Search"]'
	element :table_mod, '[class="table table-hover"]'
	element :add_section, '[class="btn btn-sm btn-success"]'
	elements :edit_section, 'body > div.container-fluid.mt-4 > div > div > div.main-data > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > a'
end

class OpenTender < SitePrism::Page
	set_url 'https://admin.opentender.io/login'
	element :ot_email, :id => 'email'
	element :ot_password, :id => 'password'
	element :ot_login_button, '#form-login > input[type=submit]'
	element :loggedin_text, '#top > div.content > div > div.content__header > h1' #Find OT login text
	element :orders, '#root > div > div > div > div.sidebar > div > nav > ul > li:nth-child(1) > a > span > span.nav__name' #order in left column
	element :place_order, '#root > div > div > div > div.sidebar > div > nav > ul > li:nth-child(1) > ul > li:nth-child(8) > a'
	element :choose_customer, 'button', text: 'Choose a customer'
	element :customer_or_promo, :id => 'query'
	element :select_customer_or_promo, '#form > div.form__submit > input'
	element :customer_or_promo_result, '#form > div.results > div > ul > li > button'
	element :select_pickup, 'button', text: 'Switch to Pickup'
	element :order_type, 'button', text: 'Choose Order Type'
	element :online_order, "#MAIN_MENU"
	element :choose_store, 'button', text: 'Choose Revenue Center'
	element :store, 'button', id: '946'
	element :menu, '#top > div.content > div > div.content__main > div > div > div > div.sticky > div'
	element :menu_items, '#a-la-carte-sides > div.menu__category__header'
	element :item, '#market-sides > div.menu__items > div:nth-child(1) > button'
	element :add_to_cart, 'button', text: 'Add To Cart'
	element :proceed_checkout, 'button', text: 'Proceed To Checkout'
	element :summary, '#order-summary'
	element :promocode, 'button', text: 'Add a Promo Code'
	element :submit_order, 'button', text: 'Submit Order'
	element :order_summary, '#summary'
	element :order_no, '#summary > div:nth-child(2) > div.receipt__value'
end